### ISSUE TITLE
Configurable permissions for files and folders created for report

### ISSUE THREAD

**Issue by cbarrerah-sogeti** [azachar/protractor-screenshoter-plugin#24]
Hi,

I'm having an issue with your plugin but not in its main functionality that works as expected (nice work).

I launch a protractor test battery that uses your plugin to generate a wonderfull html report, and when i launch it as myself from Webstorm(IDE), it creates the folders, modifies the files and all goes well.
When i launch it as a job from Jenkins, it complains about some permissions issues with some files:

> [16:25:31] I/plugins - [31m 	 Fail:  jasmine2-protractor-utils Plugin Tests [39m
[16:25:31] E/plugins - 		Failure during setup: EACCES: permission denied, mkdir '/home/barrerah/WebstormProjects/protractorTests/reports/dev/htmlReports'
[16:25:31] E/plugins - 		Error: EACCES: permission denied, mkdir '/home/barrerah/WebstormProjects/protractorTests/**reports/dev/htmlReports**'
		    at Object.fs.mkdirSync (fs.js:893:18)
		    at Function.sync (/usr/lib/node_modules/jasmine2-protractor-utils/node_modules/mkdirp/index.js:71:13)
		    at protractorUtil.setup (/usr/lib/node_modules/jasmine2-protractor-utils/index.js:314:16)
		    at resolver (/usr/lib/node_modules/protractor/lib/plugins.ts:460:52)
		    at Function.promise (/usr/lib/node_modules/protractor/node_modules/q/q.js:682:9)
		    at Plugins.safeCallPluginFun (/usr/lib/node_modules/protractor/lib/plugins.ts:471:16)
		    at promises.pluginObjs.filter.map.pluginObj (/usr/lib/node_modules/protractor/lib/plugins.ts:499:28)
		    at Array.map (native)
		    at Plugins.args [as setup] (/usr/lib/node_modules/protractor/lib/plugins.ts:497:16)
		    at q.then.then.then (/usr/lib/node_modules/protractor/lib/runner.ts:407:26)
[16:25:31] I/plugins - [31m 	 Fail:  jasmine2-protractor-utils Runtime [39m
[16:25:31] E/plugins - 		Failure during postResults: ENOENT: no such file or directory, scandir './reports/dev/htmlReports'
[16:25:31] E/plugins - 		Error: ENOENT: no such file or directory, scandir './reports/dev/htmlReports'
		    at Object.fs.readdirSync (fs.js:912:18)
		    at /usr/lib/node_modules/jasmine2-protractor-utils/index.js:344:24
		    at ManagedPromise.invokeCallback_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1366:14)
		    at TaskQueue.execute_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2970:14)
		    at TaskQueue.executeNext_ (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2953:27)
		    at asyncRun (/usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2860:25)
		    at /usr/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:676:7
		    at process._tickCallback (internal/process/next_tick.js:103:7)
[16:25:31] I/launcher - 0 instance(s) of WebDriver still running
[16:25:31] I/launcher - chrome #01 failed 1 test(s)
[16:25:31] I/launcher - overall: 1 failed spec(s)
[16:25:31] E/launcher - Process exited with error code 1

Any option to make tha folder +777 by default or configure specific permissions?

Thanks in advance

**Comment by azachar** [comment]
Hi there, 
are you sure it is this plugin? In your console I found this line:

protractorUtil.setup (/usr/lib/node_modules/jasmine2-protractor-utils/index.js:314:16)

In this fork, there is no such a code .... 

Cheers,
Andrej
