### ISSUE TITLE
Image-to-Ascii does not work

### ISSUE THREAD

**Issue by aeimer** [azachar/protractor-screenshoter-plugin#40]
Hi there,

when I run your plugin with the settings:
```
...
plugins: [{
    package: 'protractor-screenshoter-plugin',
    screenshotPath: './.reports/e2e',
    screenshotOnExpect: 'failure+success',
    screenshotOnSpec: 'failure+success',
    imageToAscii: 'failure',
    clearFoldersBeforeTest: true,
    withLogs: false, // We could set this to true => https://www.npmjs.com/package/protractor-screenshoter-plugin#withlogs-chrome-only
    writeReportFreq: 'asap',
    verbose: 'debug'
  }],
...
```

I receive the following error:
```
{ AssertionError: protocol mismatch
    at parseOptions (/vagrant/app/webFrontend/node_modules/follow-redirects/create.js:131:10)
    at H.request (/vagrant/app/webFrontend/node_modules/follow-redirects/create.js:108:19)
    at tinyreq (/vagrant/app/webFrontend/node_modules/tinyreq/lib/index.js:69:65)
    at lwipify (/vagrant/app/webFrontend/node_modules/lwipify/lib/index.js:42:9)
    at ImageParser.parse (/vagrant/app/webFrontend/node_modules/image-parser/lib/index.js:56:13)
    at /vagrant/app/webFrontend/node_modules/image-to-ascii/lib/index.js:98:40
    at doSeq (/vagrant/app/webFrontend/node_modules/one-by-one/lib/index.js:44:15)
    at oneByOne (/vagrant/app/webFrontend/node_modules/one-by-one/lib/index.js:66:5)
    at imageToAscii (/vagrant/app/webFrontend/node_modules/image-to-ascii/lib/index.js:97:5)
    at /vagrant/app/webFrontend/node_modules/protractor-screenshoter-plugin/index.js:143:25
    at WriteStream.<anonymous> (/vagrant/app/webFrontend/node_modules/protractor-screenshoter-plugin/index.js:68:17)
    at emitNone (events.js:91:20)
    at WriteStream.emit (events.js:188:7)
    at finishMaybe (_stream_writable.js:510:14)
    at afterWrite (_stream_writable.js:384:3)
    at onwrite (_stream_writable.js:374:7)
  name: 'AssertionError',
  actual: null,
  expected: 'https:',
  operator: '==',
  message: 'protocol mismatch',
  generatedMessage: false }
Please check the installation at https://github.com/IonicaBizau/image-to-ascii/blob/master/INSTALLATION.md
```

This is not your fault, it is a bug in the `parse-url` <https://github.com/IonicaBizau/parse-url> package, which is used by the `image-to-ascii` package.

The plugin classifies the file `./.reports/e2e/screenshots/b65b6de0-3fc2-11e7-beba-83e02387b4aa.png` as a remote file and wants to download it, which fails...

I have opened a PR with some tests for that: https://github.com/IonicaBizau/parse-url/pull/13 and added a issue (I know, its the wrong repo, shame on me... -.- ) https://github.com/IonicaBizau/url-local/issues/6

So if this bug is resolved, you should upgrade your dependencies ;)

Best regards,
Alex

**Comment by IonicaBizau** [comment]
> So if this bug is resolved, you should upgrade your dependencies ;)

I will release a patch release which will be automatically shipped. :grin: 

Thanks for the catch!

**Comment by IonicaBizau** [comment]
Should be fixed now! 🎉
