### ISSUE TITLE
lwip and specific node versions block install

### ISSUE THREAD

**Issue by jordandlaman** [azachar/protractor-screenshoter-plugin#59]
Looks the version of lwip you are pointing at has a problem installing on certain versions of node due to zlib and libpng versions being incompatible.  I am on 6.11.3 and for my project can't currently use nvm to switch to a different version and install it.  (that would only fix my local issues) . The version is pointed to a dead github version of lwip.  pakj/lwip seems to be more alive.  Also might consider using jimp as then you wouldn't have node trying to make calls to not node things.

```In file included from ../src/lib/png/png.c:14:
../src/lib/png/pngpriv.h:805:4: error: ZLIB_VERNUM != PNG_ZLIB_VERNUM       "-I (include path) error: see the notes in pngpriv.h"
#  error ZLIB_VERNUM != PNG_ZLIB_VERNUM \
   ^
1 error generated.
make: *** [Release/obj.target/lwip_decoder/src/lib/png/png.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/m54148/.nvm/versions/node/v6.11.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Users/m54148/.nvm/versions/node/v6.11.3/bin/node" "/Users/m54148/.nvm/versions/node/v6.11.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/m54148/sites/aa/packages/aa-client/node_modules/lwip2/node_modules/lwip
gyp ERR! node -v v6.11.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/m54148/.nvm/versions/node/v6.11.3/bin/node" "/Users/m54148/.nvm/versions/node/v6.11.3/bin/npm" "i" "lwip@0.0.9"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! lwip@0.0.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lwip@0.0.9 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lwip package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lwip
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls lwip
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/m54148/sites/aa/packages/aa-client/node_modules/lwip2/npm-debug.log
It seems like lwip failed to be intalled. Please check the errors.
@cigna/aa-client@0.88.2 /Users/m54148/sites/aa/packages/aa-client
├── UNMET PEER DEPENDENCY @angular/common@4.4.3
├── UNMET PEER DEPENDENCY @angular/core@4.4.3
├── UNMET PEER DEPENDENCY @ngrx/store@4.0.3
└── protractor-screenshoter-plugin@0.7.0

npm WARN @angular/cdk@2.0.0-beta.12 requires a peer of @angular/core@~4.4.4 but none was installed.
npm WARN @angular/cdk@2.0.0-beta.12 requires a peer of @angular/common@~4.4.4 but none was installed.
npm WARN @angular/material@2.0.0-beta.12 requires a peer of @angular/core@~4.4.4 but none was installed.
npm WARN @angular/material@2.0.0-beta.12 requires a peer of @angular/common@~4.4.4 but none was installed.
npm WARN ngrx-store-freeze@0.1.9 requires a peer of @ngrx/store@^2.2.1 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: lwip2@1.0.13 (node_modules/lwip2):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: lwip2@1.0.13 install: `node lib/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1```

**Comment by azachar** [comment]
Hi there , it’s very weird that optional package image-to-ascii that has lwip dependency is still required.

As of workaround I suggest you to read the section how to install this plugin in the readme file, especially  how  to install image-to-ascii.

Basically you will  install one dependency via sudo apt-get install and lwip stops to complain.

Let me know if that helps.

Cheers,
Andrej

**Comment by jordandlaman** [comment]
Will try and report back the results.

**Comment by azachar** [comment]
You are welcome;)
